
package com.nit.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStockService", targetNamespace = "http://endpoint.nit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IStockService {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stockProvider", targetNamespace = "http://endpoint.nit.com/", className = "com.nit.endpoint.StockProvider")
    @ResponseWrapper(localName = "stockProviderResponse", targetNamespace = "http://endpoint.nit.com/", className = "com.nit.endpoint.StockProviderResponse")
    public double stockProvider(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
