
package com.nit.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IStockServiceImplService", targetNamespace = "http://endpoint.nit.com/", wsdlLocation = "http://localhost:8080/JAXWS-CXF-Provider-ImplimentationUsingSpring-Webservices/services/stock?wsdl")
public class IStockServiceImplService
    extends Service
{

    private final static URL ISTOCKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ISTOCKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ISTOCKSERVICEIMPLSERVICE_QNAME = new QName("http://endpoint.nit.com/", "IStockServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JAXWS-CXF-Provider-ImplimentationUsingSpring-Webservices/services/stock?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ISTOCKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ISTOCKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public IStockServiceImplService() {
        super(__getWsdlLocation(), ISTOCKSERVICEIMPLSERVICE_QNAME);
    }

    public IStockServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ISTOCKSERVICEIMPLSERVICE_QNAME, features);
    }

    public IStockServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ISTOCKSERVICEIMPLSERVICE_QNAME);
    }

    public IStockServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ISTOCKSERVICEIMPLSERVICE_QNAME, features);
    }

    public IStockServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IStockServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IStockService
     */
    @WebEndpoint(name = "IStockServiceImplPort")
    public IStockService getIStockServiceImplPort() {
        return super.getPort(new QName("http://endpoint.nit.com/", "IStockServiceImplPort"), IStockService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStockService
     */
    @WebEndpoint(name = "IStockServiceImplPort")
    public IStockService getIStockServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.nit.com/", "IStockServiceImplPort"), IStockService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ISTOCKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ISTOCKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ISTOCKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
